export const SUBMIT_QUERY = "SUBMIT_QUERY";
export const PROCESS_QUERY = "PROCESS_QUERY";
export const QUERY_SUCCESS = "QUERY_SUCCESS";
export const QUERY_ERROR = "QUERY_ERROR";
export const SET_LOADING = "SET_LOADING";
export const SET_SUGGESTIONS = "SET_SUGGESTIONS";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
